<a href="https://colab.research.google.com/github/lsuhpchelp/lbrnloniworkshop2020/blob/master/day1/python_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scientific Computing with Python

In [0]:
# to bring the print function from Python 3 into Python 2.6+
from __future__ import print_function
import numpy as np

### Demostration of Numpy basic usage

In [4]:
# create a 3 by 4 matrix
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
# create a 4 by 3 matrix
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
# matrix multiplication
c = a.dot(b)
print(c)

[[ 42  48  54]
 [114 136 158]
 [186 224 262]]
